# Generated by Django 5.1.6 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='coursetitle',
            field=models.CharField(default='Unknown coursetitle', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='instructor',
            field=models.CharField(default='Unknown Instructor', max_length=100),
        ),
    ]
