# Generated by Django 5.1.6 on 2025-03-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_my', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
    ]
